server:
  port: 8090
  
#datasource:
#  url: mongodb://localhost:18100/dbbankAccount

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      host: localhost
      port: 18100
      database: dbbankAccount

eureka:
  client:
    serviceUrl.defaultZone: http://localhost:8761/eureka